### ISSUE TITLE
自分の習慣のできたできなかったをGitHubのグラフライクに管理できる

### ISSUE THREAD

**Issue by ta1kt0me** [highwide/shibaph#6]

**Comment by ta1kt0me** [comment]
良さそう。でもjQuery依存になってしまうな。
https://github.com/Kraigo/glanceyear

**Comment by highwide** [comment]
やっぱり既にあったのか＼(^o^)／

**Comment by highwide** [comment]
これもひとまずはやった。
https://github.com/highwide/shibaph/pull/54
